name: Build and test

# Run:
#
# - Every month.  Scheduling helps keep drift/issues with updates
#   to runners at bay.
# - On pushes.
#
on:
  push:
    paths:
      - "cmake/**"
      - ".github/**"

  schedule:
    - cron: '0 0 1 * *'


concurrency:
  group: "build-and-test"
  cancel-in-progress: true

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    container:
      image: jharwell/ubuntu24.04-libra:2026-02-09
    steps:
      - uses: actions/checkout@v3
      - name: Run smoke tests
        shell: bash
        run: |
          cd tests && mkdir -p build && cd build
          cmake ..
          ctest --output-on-failure -j $(nproc)

  docs:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/pages.yml
    needs: [smoke-tests]
    secrets: inherit

  create-conan-pkg:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [smoke-tests]
    steps:
      - uses: actions/checkout@v3
      - name: Create package
        shell: bash
        run: |
          pip3 install conan
          conan profile detect

          conan create \
          --user jharwell \
          --lockfile-out=package.lock \
          .

  tag-release:
    runs-on: ubuntu-latest
    needs: [smoke-tests]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Push tag
        shell: bash
        run: |
          git config --global --add safe.directory $PWD
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.event.pusher.name }}"

          git submodule update --init --remote --recursive

          PACKAGE_VERSION=$(sed -nE 's/.*LIBRA_VERSION ([0-9]+.[0-9]+.[0-9]+).*/\1/p' cmake/libra/version.cmake)

          if [ "${{ github.ref }}" = "refs/heads/devel" ]; then
            TAG_VERSION=${PACKAGE_VERSION}.beta
            TAG_MESSAGE="Development release ${TAG_VERSION}"
            git tag ${TAG_VERSION} -m "${TAG_MESSAGE}" -f
            git push -o ci.skip origin ${TAG_VERSION} -f
          elif [ "${{ github.ref }}" = "refs/heads/master" ]; then
            TAG_VERSION=${PACKAGE_VERSION}
            TAG_MESSAGE="Release ${TAG_VERSION}"
            git tag ${TAG_VERSION} -m "${TAG_MESSAGE}"
            git push -o ci.skip origin ${TAG_VERSION}
          fi
